#!/usr/bin/env bash
# build-config.sh — Generate runtime config from environment variables.
#
# Cloudflare Pages runs this as the build command. It reads KIT_KEY from the
# Pages env vars (Secret) and writes assets/arc-appkit-config.js with the value
# baked in. The generated file is gitignored.
#
# Local dev: copy assets/arc-appkit-config.js.example → assets/arc-appkit-config.js
# and paste your kit key manually. This script is NOT meant to run locally.

set -euo pipefail

CONFIG_FILE="assets/arc-appkit-config.js"

# Pull from env (set by Cloudflare Pages Settings → Environment variables)
KIT_KEY="${KIT_KEY:-}"
NETWORK="${APPKIT_NETWORK:-Arc_Testnet}"

if [[ -z "$KIT_KEY" ]]; then
  # Local dev safety: don't overwrite an existing config file (which may have
  # the real kit key the developer manually pasted from .example).
  if [[ -f "$CONFIG_FILE" ]]; then
    echo "ℹ️  KIT_KEY env not set; existing $CONFIG_FILE preserved (local dev mode)."
    exit 0
  fi
  echo "⚠️  KIT_KEY env var not set — writing placeholder. Set the env in Cloudflare"
  echo "    Pages → Settings → Environment variables (as Secret), then redeploy."
fi

mkdir -p assets

# Use printf instead of heredoc to avoid CRLF issues on Windows runners.
{
  printf '// Auto-generated by scripts/build-config.sh — DO NOT COMMIT or edit by hand.\n'
  printf '// Local dev: copy arc-appkit-config.js.example and edit.\n'
  printf '// Production: Cloudflare Pages build script writes this from env vars.\n'
  printf 'window.ARC_APPKIT_CONFIG = Object.freeze({\n'
  printf '  kitKey: "%s",\n' "$KIT_KEY"
  printf '  network: "%s"\n' "$NETWORK"
  printf '});\n'
} > "$CONFIG_FILE"

echo "✓ Built $CONFIG_FILE (kit key length: ${#KIT_KEY})"
