#!/usr/bin/env bash
# build-config.sh — Generate runtime config for Circle App Kit (browser side).
#
# IMPORTANT (security): The real KIT_KEY is NEVER written to the browser-side
# config file. Instead, the browser uses a placeholder value, and all calls to
# api.circle.com are routed through /api/circle-proxy (a Pages Function in
# functions/api/circle-proxy/[[path]].js) which injects the real KIT_KEY from
# env.KIT_KEY server-side.
#
# This script just writes the network name + a placeholder kitKey so the SDK's
# client-side validation passes. The placeholder is meaningless — proxy adds
# the real one before forwarding to Circle.
#
# Local dev: copy assets/arc-appkit-config.js.example → arc-appkit-config.js.
# Production: Cloudflare Pages build runs this script.

set -euo pipefail

CONFIG_FILE="assets/arc-appkit-config.js"
NETWORK="${APPKIT_NETWORK:-Arc_Testnet}"

# Sanity check: ensure KIT_KEY is set in Cloudflare env so the proxy works
# (the proxy reads env.KIT_KEY at request time — without it, swap calls fail).
KIT_KEY="${KIT_KEY:-}"
if [[ -z "$KIT_KEY" ]]; then
  if [[ -f "$CONFIG_FILE" ]]; then
    echo "ℹ️  KIT_KEY env not set; existing $CONFIG_FILE preserved (local dev mode)."
    exit 0
  fi
  echo "⚠️  KIT_KEY env var not set in Cloudflare env. The proxy at"
  echo "    /api/circle-proxy will return 500 until KIT_KEY is added as a Secret."
fi

mkdir -p assets

# Write a CLIENT-SAFE config — kit key is just a placeholder, real one lives
# only in Cloudflare env (read by the Pages Function proxy).
{
  printf '// Auto-generated by scripts/build-config.sh — DO NOT COMMIT or edit by hand.\n'
  printf '//\n'
  printf '// SECURITY: The kitKey value below is a PLACEHOLDER, not a real key.\n'
  printf '// Real KIT_KEY lives in Cloudflare env var (Secret) and is added\n'
  printf '// server-side by the proxy at /api/circle-proxy. Browser never sees it.\n'
  # Placeholder must match Circle SDK's client-side regex `KIT_KEY:<id>:<secret>`.
  # Real key is added server-side by the Pages Function proxy. The values below
  # are obvious dummies so anyone reading source knows it's not the real key.
  printf 'window.ARC_APPKIT_CONFIG = Object.freeze({\n'
  printf '  kitKey: "KIT_KEY:proxied_in_cloudflare_function:not_a_real_key",\n'
  printf '  network: "%s",\n' "$NETWORK"
  printf '  proxyHealthy: %s\n' "$([[ -n "$KIT_KEY" ]] && echo "true" || echo "false")"
  printf '});\n'
} > "$CONFIG_FILE"

echo "✓ Built $CONFIG_FILE (proxyHealthy: $([[ -n "$KIT_KEY" ]] && echo "true" || echo "false"))"
